CFLAGS= -g -Wall -O3 -std=gnu11
LDLIBS= -l sqlite3

all: count-players week-score email-lineup 

count-players:

week-score:

email-lineup:

clean:
	$(RM) count-players
	$(RM) week-score
	$(RM) email-lineup
